/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package page;

import db.table.BookDAO;
import db.table.BookDTO;
import db.table.CartDAO;
import db.view.v_cartDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Book extends javax.swing.JFrame implements ActionListener{
    BookDTO dto;
    String userid;
    Main m;
    Cart c;
    String ISBN13;
    int qty;
    Boolean fromCart=false;
    
    /**
     * Creates new form Select
     */
    
    public Book() {
        super("도서 목록");
        fromCart=false;
        initComponents();
        init();
        addEvent();
        showData();
    }
    
    
    public Book(String ISBN13) {
        super("도서 목록");
        this.ISBN13=ISBN13;
        fromCart=false;
        initComponents();
        init();
        addEvent();
        showData();
    }
    
    public Book(String ISBN13, Boolean fromCart) {
        super("도서 목록");
        this.ISBN13=ISBN13;
        this.fromCart=true;
        initComponents();
        init();
        addEvent();
        showData();
    }
    
    public Book(String ISBN13, String userid) {
        super("도서 목록");
        this.ISBN13=ISBN13;
        this.userid=userid;
        fromCart=false;
        initComponents();
        init();
        addEvent();
        showData();
    }
    
    //로그인 안 한 상태로 검색 후 Book에서 로그인했을 때 Main도 로그인처리하기 위함
    public Book(String ISBN13, String userid, Main m) {
        super("도서 목록");
        this.ISBN13=ISBN13;
        this.userid=userid;
        this.m=m;
        initComponents();
        init();
        addEvent();
        showData();
    }
    
    public Book(String ISBN13, String userid, Cart c) {
        this();
        this.ISBN13=ISBN13;
        this.userid=userid;
        this.c=c;
        showData();
        
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfTitle = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfAuthor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfPublisher = new javax.swing.JTextField();
        lbFullPrice = new javax.swing.JLabel();
        lbPrice = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btQtyUp = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfQty = new javax.swing.JTextField();
        tfSelectedQty = new javax.swing.JTextField();
        btQtyDown = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbISBN13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbKind = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lbPublisherDate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cardPanel = new javax.swing.JPanel();
        cardNull = new javax.swing.JPanel();
        cardUserid = new javax.swing.JPanel();
        lbUserid = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cardPanel2 = new javax.swing.JPanel();
        cardNull2 = new javax.swing.JPanel();
        cardButton = new javax.swing.JPanel();
        btCart = new javax.swing.JButton();
        btDirectOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel3.setText("도서명");

        jLabel4.setText("저자/아티스트");

        jLabel5.setText("출판사");

        lbFullPrice.setFont(new java.awt.Font("굴림", 2, 12)); // NOI18N
        lbFullPrice.setText("14,000");

        lbPrice.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        lbPrice.setText("12,000");

        btQtyUp.setText(">");

        jLabel12.setText("권");

        jLabel11.setText("권");

        tfQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQtyActionPerformed(evt);
            }
        });

        tfSelectedQty.setText("1");
        tfSelectedQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSelectedQtyActionPerformed(evt);
            }
        });

        btQtyDown.setText("<");

        jLabel9.setText("재고");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btQtyDown, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tfQty)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tfSelectedQty, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btQtyUp))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfQty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btQtyUp)
                    .addComponent(jLabel12)
                    .addComponent(tfSelectedQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btQtyDown)))
        );

        jLabel13.setText("ISBN");

        lbISBN13.setText("jLabel14");

        jLabel15.setText("분류");

        lbKind.setText("ㅇㅇ/ㅇㅇ/ㅇㅇ");

        jLabel17.setText("출간일");

        lbPublisherDate.setText("jLabel2");

        jLabel1.setFont(new java.awt.Font("굴림", 2, 12)); // NOI18N
        jLabel1.setText("정가");

        jLabel2.setFont(new java.awt.Font("굴림", 1, 12)); // NOI18N
        jLabel2.setText("판매가");

        jLabel6.setText("원");

        jLabel8.setText("원");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTitle)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbFullPrice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbPrice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tfAuthor)
                            .addComponent(tfPublisher)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbISBN13, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbKind))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbPublisherDate)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbFullPrice)
                    .addComponent(jLabel2)
                    .addComponent(lbPrice)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(lbPublisherDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(lbKind))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lbISBN13)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.jpg"))); // NOI18N

        cardPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout cardNullLayout = new javax.swing.GroupLayout(cardNull);
        cardNull.setLayout(cardNullLayout);
        cardNullLayout.setHorizontalGroup(
            cardNullLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        cardNullLayout.setVerticalGroup(
            cardNullLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        cardPanel.add(cardNull, "card3");

        jLabel7.setText("님");

        javax.swing.GroupLayout cardUseridLayout = new javax.swing.GroupLayout(cardUserid);
        cardUserid.setLayout(cardUseridLayout);
        cardUseridLayout.setHorizontalGroup(
            cardUseridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardUseridLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lbUserid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        cardUseridLayout.setVerticalGroup(
            cardUseridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardUseridLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardUseridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUserid)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardPanel.add(cardUserid, "card2");

        cardPanel2.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout cardNull2Layout = new javax.swing.GroupLayout(cardNull2);
        cardNull2.setLayout(cardNull2Layout);
        cardNull2Layout.setHorizontalGroup(
            cardNull2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );
        cardNull2Layout.setVerticalGroup(
            cardNull2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
        );

        cardPanel2.add(cardNull2, "card2");

        btCart.setText("장바구니 담기");

        btDirectOrder.setText("바로구매");
        btDirectOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDirectOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cardButtonLayout = new javax.swing.GroupLayout(cardButton);
        cardButton.setLayout(cardButtonLayout);
        cardButtonLayout.setHorizontalGroup(
            cardButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btCart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btDirectOrder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cardButtonLayout.setVerticalGroup(
            cardButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCart)
                    .addComponent(btDirectOrder))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardPanel2.add(cardButton, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231)
                .addComponent(cardPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfSelectedQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSelectedQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSelectedQtyActionPerformed

    private void tfQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQtyActionPerformed

    private void btDirectOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDirectOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btDirectOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCart;
    private javax.swing.JButton btDirectOrder;
    private javax.swing.JButton btQtyDown;
    private javax.swing.JButton btQtyUp;
    private javax.swing.JPanel cardButton;
    private javax.swing.JPanel cardNull;
    private javax.swing.JPanel cardNull2;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JPanel cardPanel2;
    private javax.swing.JPanel cardUserid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lbFullPrice;
    private javax.swing.JLabel lbISBN13;
    private javax.swing.JLabel lbKind;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbPublisherDate;
    private javax.swing.JLabel lbUserid;
    private javax.swing.JTextField tfAuthor;
    private javax.swing.JTextField tfPublisher;
    private javax.swing.JTextField tfQty;
    private javax.swing.JTextField tfSelectedQty;
    private javax.swing.JTextField tfTitle;
    // End of variables declaration//GEN-END:variables
    
    
    public void setUserid(String userid) {
        this.userid = userid;
        showData();
    }
    
    void setISBN13(String ISBN13) {
        this.ISBN13=ISBN13;
        showData();
    }
    
    private void showData() {
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); 
        BookDAO dao = new BookDAO();
        
        try {
            dto=dao.selectISBN(ISBN13);
               } catch (SQLException ex) {
            ex.printStackTrace();
        }
        
        String title=dto.getTitle();
        String author=dto.getAuthor();
        String publisher=dto.getPublisher();
        int fullPrice=dto.getFullprice();
        int price=dto.getPrice();

        String publisherDate=new SimpleDateFormat("yyyy/MM/dd").format(dto.getPublisherDate());
        String kind=dto.getKind();
        ISBN13=dto.getISBN13();
        int qty=dto.getQty();

        //데이터를 화면에 뿌리기
        tfTitle.setText(title);
        tfAuthor.setText(author);
        tfPublisher.setText(publisher);
        lbFullPrice.setText(fullPrice+"");
        lbPrice.setText(price+"");
        lbPublisherDate.setText(publisherDate);
        lbKind.setText(kind);
        lbISBN13.setText(ISBN13);
        tfQty.setText(qty+"");

        cardPanel.removeAll();
        cardPanel.add(cardNull);
        
        System.out.println("fromCart="+fromCart);
        
        if(fromCart) {
            cardPanel2.removeAll();
            cardPanel2.add(cardNull2);
        }else{
            cardPanel2.removeAll();
            cardPanel2.add(cardButton);
        }
    }

    private void addEvent() {
        btCart.addActionListener(this);
        btQtyDown.addActionListener(this);
        btQtyUp.addActionListener(this);
        btDirectOrder.addActionListener(this);
            
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==btCart) {
            //로그인된 상태인지 체크
            if(userid==null || userid.isEmpty()) {
                JOptionPane.showMessageDialog(this, "로그인이 필요한 서비스입니다.");
                Login l = new Login(m, this);
                l.setVisible(true);
                
                return;
            }
            
            //수량이 0 이상인지 체크
            qty=Integer.parseInt(tfSelectedQty.getText());
            if(qty<0) {
                JOptionPane.showMessageDialog(this, "수량은 0 이상이여야 합니다");
                return;
            }
                
            addCart();
        }
        
        //수량 버튼 
        if(e.getSource()==btQtyDown) {
            qty=Integer.parseInt(tfSelectedQty.getText());
            if(qty<=0) {
                tfSelectedQty.setText("0");
            }else{
                qty-=1;
                tfSelectedQty.setText(qty+"");
            }
        }
        if(e.getSource()==btQtyUp) {
            qty=Integer.parseInt(tfSelectedQty.getText());
            qty+=1;
            tfSelectedQty.setText(qty+"");
        }
        
        //바로구매
        if(e.getSource()==btDirectOrder) {
            
            //로그인된 상태인지 체크
            if(userid==null || userid.isEmpty()) {
                JOptionPane.showMessageDialog(this, "로그인이 필요한 서비스입니다.");
                Login l = new Login(m, this);
                l.setVisible(true);
                
                return;
            }
            
            BookDAO dao=new BookDAO();
            int isEnoughQty=0;
            try {
                System.out.println("isEnough에서 매개변수 qty");
                isEnoughQty=dao.isEnoughQty(ISBN13, qty);
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            if(isEnoughQty>0) { //주문수량이 재고 수량을 초과하는게 있다는 소리
                JOptionPane.showMessageDialog(this, "재고 수량이 주문 수량보다 많습니다!");
                String qtyMessage="재고 수량: "+isEnoughQty+", 주문 수량: "+qty;
                JOptionPane.showMessageDialog(this, qtyMessage);
                    
            }else{              
                v_cartDTO dto=new v_cartDTO();
                dto.setUserid(userid);
                dto.setISBN13(ISBN13);
                dto.setQty(qty);
                dto.setPrice(Integer.parseInt(lbPrice.getText()));
                dto.setTitle(tfTitle.getText());
                
                ArrayList<v_cartDTO> list=new ArrayList<>();
                list.add(dto);
                
                Order o = new Order(userid, list, this);
                o.setVisible(true);
            }
        }
    }
    
    private void addCart() {
        CartDAO dao=new CartDAO();
        ISBN13=lbISBN13.getText();
        int qty=Integer.parseInt(tfSelectedQty.getText());
        
        int isDup=0;
        //동일 데이터가 존재하는지?
        try {
            isDup=dao.selectCart(userid, ISBN13);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        if(isDup==1) {
            JOptionPane.showMessageDialog(this, "같은 도서가 이미 장바구니에 존재합니다!");
            
            Cart ca = new Cart(m, userid);
            ca.setVisible(true);
        }
        else{
            try {
                dao.insertCart(userid, ISBN13, qty);
                
                int goCart = JOptionPane.showConfirmDialog(this, "해당 도서가 장바구니에 담겨졌습니다.\n"
                    + "장바구니로 가시겠습니까?", 
                    "알림창", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

                if(goCart==0) {
                    this.dispose();
                    Cart c = new Cart(m, userid);
                    c.setVisible(true);
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            
        }   
    }//addCart()

    private void init() {
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

}

