/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package page;

import db.table.CartDAO;
import db.view.qtyTempDTO;
import db.view.v_cartDTO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author STU-05
 */
public class Cart extends javax.swing.JFrame implements ActionListener {
    CartDAO dao;
    String userid;
    Main m;
    Book b;
    
    String[] colNames= {"도서명", "ISBN", "가격", "수량"};
    DefaultTableModel model=null;
    
    /**
     * Creates new form Cart
     * 
     */
    
    public Cart() {
        super("장바구니");
        initComponents();
        init();
        addEvent();
    }

    public Cart(Main m, String userid) {
        super("장바구니");
        this.userid=userid;
        this.m=m;
        initComponents();
        init();
        addEvent();
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btQtyDown = new javax.swing.JButton();
        tfQty = new javax.swing.JTextField();
        btQtyUp = new javax.swing.JButton();
        btSave = new javax.swing.JButton();
        btBookDetail = new javax.swing.JButton();
        tfISBN13 = new javax.swing.JTextField();
        lbISBN13 = new javax.swing.JLabel();
        btDelete = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btLogout = new javax.swing.JButton();
        lbUserid = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tfTotalPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btBuyAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "장바구니", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("굴림", 0, 14))); // NOI18N

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "도서명", "ISBN", "가격", "수량"
            }
        ));
        scrollPane.setViewportView(table);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("선택된 도서"));

        jLabel1.setText("도서명");

        jLabel2.setText("가격");

        jLabel3.setText("수량");

        btQtyDown.setFont(new java.awt.Font("굴림", 0, 8)); // NOI18N
        btQtyDown.setText("<");

        tfQty.setText("00");

        btQtyUp.setFont(new java.awt.Font("굴림", 0, 8)); // NOI18N
        btQtyUp.setText(">");

        btSave.setFont(new java.awt.Font("굴림", 0, 10)); // NOI18N
        btSave.setText("저장");

        btBookDetail.setFont(new java.awt.Font("굴림", 0, 10)); // NOI18N
        btBookDetail.setText("도서 자세히 보기");

        lbISBN13.setText("ISBN");

        btDelete.setText("장바구니에서 삭제");
        btDelete.setFocusable(false);
        btDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(lbISBN13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfISBN13)
                            .addComponent(btBookDetail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfPrice, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btQtyDown)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btQtyUp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSave))
                            .addComponent(tfTitle))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfISBN13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbISBN13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btQtyDown)
                    .addComponent(tfQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btQtyUp)
                    .addComponent(btSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBookDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btDelete))
        );

        btLogout.setText("로그아웃");
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });

        jLabel4.setText("님");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbUserid, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUserid, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btLogout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo1s.jpg"))); // NOI18N

        jLabel7.setText("총 가격");

        jLabel5.setText("원");

        btBuyAll.setText("장바구니에 담긴 도서 구매하기");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel5))
                    .addComponent(btBuyAll, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBuyAll)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 75, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("삭제");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBookDetail;
    private javax.swing.JButton btBuyAll;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btQtyDown;
    private javax.swing.JButton btQtyUp;
    private javax.swing.JButton btSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbISBN13;
    private javax.swing.JLabel lbUserid;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable table;
    private javax.swing.JTextField tfISBN13;
    private javax.swing.JTextField tfPrice;
    private javax.swing.JTextField tfQty;
    private javax.swing.JTextField tfTitle;
    private javax.swing.JTextField tfTotalPrice;
    // End of variables declaration//GEN-END:variables

    private void init() {
        dao = new CartDAO();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        lbUserid.setText(userid);
        
        model = new DefaultTableModel();
        
        try {
        showAll();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    private void addEvent() {
        btLogout.addActionListener(this);
        
        table.addMouseListener(new EventHandler());
        
        btBuyAll.addActionListener(this);
        
        btQtyDown.addActionListener(this);
        btQtyUp.addActionListener(this);
        btSave.addActionListener(this);
        btBookDetail.addActionListener(this);
        btDelete.addActionListener(this);
        
        
    }

    private void showAll() throws SQLException {
        
        ArrayList<v_cartDTO> list=dao.selectAll(userid);
        
        if(list==null || list.isEmpty()){
            JOptionPane.showMessageDialog(this, "장바구니에 담긴 도서가 없습니다.");
        }
        int totalPrice=0;    
        DecimalFormat df = new DecimalFormat("#,###");
        String[][] data=new String[list.size()][4];
        for(int i=0;i<list.size();i++) {
            v_cartDTO dto=list.get(i);

            data[i][0]=dto.getTitle();
            data[i][1]=dto.getISBN13();
            data[i][2] = df.format(dto.getPrice());   
            data[i][3]=dto.getQty()+"";


            totalPrice+=dto.getPrice()*dto.getQty();
        }

        tfTotalPrice.setText(df.format(totalPrice));
        model.setDataVector(data, colNames);
        table.setModel(model);
        
    }

    private void clear_tf() {
        tfTitle.setText("");
        tfISBN13.setText("");
        tfPrice.setText("");
        tfQty.setText("");
    }
    
    class EventHandler extends MouseAdapter{

        @Override
        public void mouseClicked(MouseEvent e) {
            int row = table.getSelectedRow();
            tfTitle.setText((String) table.getValueAt(row, 0));
            tfISBN13.setText((String) table.getValueAt(row, 1));
            tfPrice.setText((String) table.getValueAt(row, 2));
            tfQty.setText((String) table.getValueAt(row, 3));
        }
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        //로그아웃
        if(e.getSource()==btLogout) {
            JOptionPane.showMessageDialog(this, "main 화면으로 돌아갑니다.");
            userid="";
            this.dispose();
                if(m!=null) {
                    m.setReload(userid);
                }
                if(b!=null) {
                    b.dispose();
                }
        }//if
        
        //수량 변경
        if(e.getSource()==btQtyDown) {
            int qty=Integer.parseInt(tfQty.getText());
            if(qty<=0) {
                tfQty.setText("0");
            }else{
                qty-=1;
                tfQty.setText(qty+"");
            }
        }
        if(e.getSource()==btQtyUp) {
            int qty=Integer.parseInt(tfQty.getText());
            qty+=1;
            tfQty.setText(qty+"");
        }
        
        //수량 변경 저장
        if(e.getSource()==btSave) {
            String ISBN13=tfISBN13.getText();
            int qty=Integer.parseInt(tfQty.getText());
            
            //수량이 0 이상인지 체크
            if(qty<0) {
                JOptionPane.showMessageDialog(this, "수량은 0 이상이여야 합니다");
                return;
            }
            
            try {
                int cnt=dao.updateCart(userid, ISBN13, qty);
                JOptionPane.showMessageDialog(this, "저장 완료!");
                
                showAll();
                
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
        
        //도서 자세히 보기
        if(e.getSource()==btBookDetail) {
            String ISBN13=tfISBN13.getText();
            if(ISBN13==null || ISBN13.isEmpty()) {
                JOptionPane.showMessageDialog(this, "도서를 선택해야 합니다!");
                return;
            }
            boolean fromCart=true;
            Book b = new Book(ISBN13, fromCart);
            b.setVisible(true);
        }
        
        //장바구니에서 도서 삭제
        if(e.getSource()==btDelete) {
            String ISBN13=tfISBN13.getText();
            CartDAO dao = new CartDAO();
            
            try {
                int cnt=dao.deleteBook(userid, ISBN13);
                if(cnt==0) {
                    return;
                }else{
                    JOptionPane.showMessageDialog(this, "해당 도서를 장바구니에서 삭제하였습니다.");
                    clear_tf();
                    showAll();
                }
                
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
        
        //도서 구매하기
        if(e.getSource()==btBuyAll) {
            try {
                System.out.println("Cart selectAll에서 userid="+userid);
                ArrayList<v_cartDTO> list=dao.selectAll(userid);
                if(list==null || list.isEmpty()){
                    JOptionPane.showMessageDialog(this, "장바구니에 담긴 도서가 없습니다!");
                return;
                }
                
                ArrayList<qtyTempDTO> qtyList=dao.isEnoughQty(userid);
                
                if(!qtyList.isEmpty()) { //주문수량이 재고 수량을 초과하는게 있다는 소리
                    JOptionPane.showMessageDialog(this, "재고 수량이 주문 수량보다 많습니다!");
                    for(int i=0;i<qtyList.size();i++) {
                        qtyTempDTO dto=qtyList.get(i);
                        
                        String title=dto.getTitle();
                        String bQty=dto.getbQty()+"";
                        String cQty=dto.getcQty()+"";
                        
                        String qtyMessage="도서명: "+title+
                                "\n재고 수량: "+bQty+", 주문 수량: "+cQty;
                        JOptionPane.showMessageDialog(this, qtyMessage);
                    }
                }else{               
                    Order o = new Order(userid, list, this);
                    o.setVisible(true);
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
        
    }
}
